#/bin/bash

NETWORK=ZENITH SUBNETWORK=MAINNET COIN=ZENITH \
	ETHEREUM_JSONRPC_VARIANT=geth COIN_B=DAI \
	ETHEREUM_JSONRPC_HTTP_URL=http://15.152.54.105:8545 \
	MIX_ENV=prod \
	LOGO=/images/blockscout_logo.svg \
	ETHEREUM_JSONRPC_WS_URL=ws://15.152.54.105:8546 \
	ETHEREUM_JSONRPC_TRACE_URL=http://15.152.54.105:8545 \
	SECRET_KEY_BASE=secret PORT=4000 BLOCK_TRANSFORMER=clique ECTO_USE_SSL=false \
	APPS_MENU=false CHECKSUM_ADDRESS_HASHES=true \
	ADDRESS_TRANSACTIONS_GAS_USAGE_COUNTER_CACHE_PERIOD=60 \
	TOTAL_GAS_USAGE_CACHE_PERIOD=60 \
	TXS_COUNT_CACHE_PERIOD=60 \
	TOKEN_TRANSFERS_COUNTER_CACHE_PERIOD=60 \
	ADDRESS_COUNT_CACHE_PERIOD=60 \
	ADDRESS_TRANSACTIONS_CACHE_PERIOD=60 EMISSION_FORMAT=DEFAULT POOL_SIZE=40 \
	UNCLES_IN_AVERAGE_BLOCK_TIME=false \
	LINK_TO_OTHER_EXPLORERS={} SUPPORTED_CHAINS={} BLOCK_COUNT_CACHE_PERIOD=60 \
	EXTERNAL_APPS=[] \
	ADDRESS_TRANSACTIONS_GAS_USAGE_COUNTER_CACHE_PERIOD=60 \
	POOL_SIZE_API=10 HEART_BEAT_TIMEOUT=30 make start
